#TOKEN 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
name: "Get releases"
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  "PocketMine-Client":
    name: "Get releases"
    runs-on: ubuntu-latest

    steps:
      - name: "Get PocketMine-Client"
        id: "pocketmine_client"

        run: |
          echo ::set-output name=REPO::PocketMine-Client
          echo ::set-output name=FILE::PocketMine-Client.phar

          wget -q --auth-no-challenge --header='Accept:application/octet-stream' \
          https://${{ secrets.TOKEN }}:@api.github.com/repos/${{ steps.metadata.outputs.REPO }}/releases/assets/`gh_curl -s $GITHUB/repos/${{ steps.metadata.outputs.REPO }}/releases | jq ". | map(select(.tag_name == \"dev\"))[0].assets | map(select(.name == \"${{ steps.metadata.outputs.FILE }}\"))[0].id"` \
          -O $2

          wget -q --auth-no-challenge --header='Accept:application/octet-stream' \
          https://${{ secrets.TOKEN }}:@api.github.com/repos/${{ steps.metadata.outputs.REPO }}/releases/assets/`gh_curl -s $GITHUB/repos/${{ steps.metadata.outputs.REPO }}/releases | jq ".[0].assets | map(select(.name == \"${{ steps.metadata.outputs.FILE }}\"))[0].id"` \
          -O $2

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.metadata.outputs.VERSION }}"
          prerelease: false
          title: "Release v${{ steps.metadata.outputs.VERSION }}"
          files: |
            out/*.phar
